// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
export const environment = {
    webalytics: {
        siteId: "wb_live_a46e29bd44d3c2e03845",
        host: "https://44.198.214.153.nip.io",
        publicToken: "wb_pub_live_59624ef94f7b3572025a54d03b792ffa",
        environment: "development",
    },
};
