// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// This file is regenerated on every build from Vercel env vars. Empty defaults here
// mean the tracker and dashboard are disabled when running locally without env vars.
export const environment = {
    webalytics: {
        siteId: '',
        host: '',
        publicToken: '',
        environment: 'development',
    },
};
