#!/usr/bin/env node
/* eslint-disable */
const fs = require('fs');
const path = require('path');

const envDir = path.resolve(__dirname, '..', 'src', 'environments');
const envFile = path.join(envDir, 'environment.ts');

const webalyticsSiteId = process.env.WEBALYTICS_SITE_ID || '';
const webalyticsHost = process.env.WEBALYTICS_HOST || '';
const webalyticsPublicToken = process.env.WEBALYTICS_PUBLIC_TOKEN || '';
const vercelEnv = process.env.VERCEL_ENV || 'development';

if (!webalyticsSiteId || !webalyticsHost) {
    console.warn(
        '[generate-env] WEBALYTICS_SITE_ID or WEBALYTICS_HOST not set. ' +
        'Webalytics tracker will be disabled for this build.'
    );
}
if (!webalyticsPublicToken) {
    console.warn(
        '[generate-env] WEBALYTICS_PUBLIC_TOKEN not set. ' +
        'Analytics dashboard will be disabled for this build.'
    );
}

const contents = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
export const environment = {
    webalytics: {
        siteId: ${JSON.stringify(webalyticsSiteId)},
        host: ${JSON.stringify(webalyticsHost)},
        publicToken: ${JSON.stringify(webalyticsPublicToken)},
        environment: ${JSON.stringify(vercelEnv === 'production' ? 'production' : 'development')},
    },
};
`;

fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(envFile, contents, 'utf8');
console.log(`[generate-env] Wrote ${envFile} (env=${vercelEnv})`);
